### ISSUE TITLE
Update today (which was for both games) broke the tool

### ISSUE THREAD

**Issue by Reshirou** [c0dycode/Borderlands-Hex-Multitool#9] opened 2019-04-03 18:17 UTC
Crashes after hitting apply. Pretty straightforward. Update was for support on the free UHD DLCs.

**Comment by Reshirou** [comment] 2019-04-03 18:22
I should add that manually hex editing the EXEs can re-enable modding, though; the BLCMM program cannot automatically do it anymore, but the strings to replace are actually all still the same, and work. I tested it with TPS and technically not 2 yet (can't while the UHD DLC downloads) but I assume BL2 modding also still works with the manual hex edits.

A work-around that might be easier than updating your program for now could be you just saying which strings get replaced with what. Level cap is probably the most used feature, followed by inventory space and sanity check.

**Comment by SnerdBurglar** [comment] 2019-04-03 18:27
Experiencing similar issue, toll applies changes but when game is launched gets to the loading screen with the main 4 characters on it then stops responding, happens on 1.18 and 1.20. Also the tool has been acting strange when files are verified tried posted solution of the %localappdata% and deleting them. Sometimes restoring from the backup gets the tool to pick up correctly other than that all the data is zeroed out.

**Comment by PatrickdeBie** [comment] 2019-04-03 19:21
Same problem here. Also the dropdownlist for the Console and Set Command editing is empty. So I cannot set it to a preferred key on my keyboard (like ~ ).

**Comment by c0dycode** [comment] 2019-04-03 20:26
Apologies for the late reply here.
I'm working on updating the tool since the update came out. I'll keep you updated here if I have an update ready for testing :)

**Comment by MrSunwolf** [comment] 2019-04-03 22:38
blcmm seems to be working cause i have my console set up again but like everyone else said hex editer broke on us 

i wonder is there a alternate fix until c0dycode fixes this? heck i was hoping to play some more reborn mod

**Comment by c0dycode** [comment] 2019-04-03 22:49
[BL Hex-Multitool .NET 4.5 - UHD BL2 Beta.zip](https://github.com/c0dycode/Borderlands-Hex-Multitool/files/3041030/BL.Hex-Multitool.NET.4.5.-.UHD.BL2.Beta.zip)

Alright guys, here's the first beta for testing.
Unless I've missed something, everything appears to be working as expected. If you notice any issues, feel free to open up a new issue.

FOR NOW this is ONLY for BL2. TPS is disabled in this version, but will be worked on now 👍

**Comment by HairyPalms** [comment] 2019-04-03 23:26
Max rank, backpack space, and sanity checks all work fine. Haven't checked anything else though. Thanks man great work!

**Comment by MyJumpsSuck** [comment] 2019-04-03 23:42
It doesn't seem to work for me as I have the 1.8 version from blmcm and no matter what I try to do with that version it freezes, anyone have any idea how to patch the new version into blmcm? Also thanks for all of the work on this project!!

**Comment by Default-Devv** [comment] 2019-04-03 23:43
After attempting it, the console still does not work, and everything else has still yet to be tested.

**Comment by c0dycode** [comment] 2019-04-03 23:45
@MyJumpsSuck The one that is shipped via BLCMM won't work with the UHD Updated exe. Try the one attached above.

@Default-Devv As in the console doesn't open at all? Or you can't use commands?

**Comment by Default-Devv** [comment] 2019-04-03 23:45
@c0dycode Can't exec, still stuck on doing "say"

**Comment by c0dycode** [comment] 2019-04-03 23:47
Alrighty, can you verify your gamefiles via steam, so you get a new exe and upload that one and send me the link? Then I can look into whether the Patterns work or not 👍

**Comment by Default-Devv** [comment] 2019-04-03 23:47
Gotcha, give me a few minutes.

**Comment by MyJumpsSuck** [comment] 2019-04-03 23:52
I do have the older version of the hex,that my not be the problem idk, Im having the same problem default is, I put in exec bl2reborn.txt and it just puts it in the chat.

**Comment by MyJumpsSuck** [comment] 2019-04-04 00:01
How do I send you the link?

**Comment by HairyPalms** [comment] 2019-04-04 00:16
Oh as a note i did not use the program to enable the console nor to enable hex editing so my test didn't include that

**Comment by Default-Devv** [comment] 2019-04-04 00:16
@c0dycode here ya go

[bl2.zip](https://github.com/c0dycode/Borderlands-Hex-Multitool/files/3041207/bl2.zip)

**Comment by c0dycode** [comment] 2019-04-04 00:18
@Default-Devv Alright, thanks. Don't worry, I deleted it on purpose. exe's are per user :)

**Comment by Default-Devv** [comment] 2019-04-04 00:18
@c0dycode Oh okay, did not know that haha! Thanks.

**Comment by c0dycode** [comment] 2019-04-04 00:19
I'll look into it in a bit 👍

**Comment by MyJumpsSuck** [comment] 2019-04-04 00:19
Will Blcmm have to ship  out a new version, by the way thanks for spending your time fixing this.

**Comment by c0dycode** [comment] 2019-04-04 00:20
Yes, BLCMM will include a new version once it receives an update and once Multitool works as intended 👍

**Comment by HeinzKetchupz** [comment] 2019-04-04 02:43
Gday, Is there a way to open BLCMM and set it to use hex edit 1.20 
Keeps opening 1.18. Tried just uninstalling 1.18

**Comment by c0dycode** [comment] 2019-04-04 02:46
Not from within BLCMM currently. The standalone version attached above is the only way at the moment.

**Comment by HeinzKetchupz** [comment] 2019-04-04 02:48
Yeah ive got 1.20 working right. Just I cant get it to work within BL2. Not sure if its what I did or if it has to do with BLCMM

**Comment by HeinzKetchupz** [comment] 2019-04-04 02:52
Ignore this I just didnt hit save rip
Great work man!

**Comment by KatNDusty** [comment] 2019-04-04 03:04
Did we find a way to get the command "exec ..." to work without it just posting in chat? Or is that still in the works?

**Comment by c0dycode** [comment] 2019-04-04 03:05
That depends. If you've tried the attached version above and it doesn't work, then I still need to investigate that.  I am still working on initial support for TPS currently.

**Comment by KatNDusty** [comment] 2019-04-04 03:09
Version 1.2 right?

**Comment by KatNDusty** [comment] 2019-04-04 03:10
And thanks for all your hard work! :) Very quick to react! Much appreciation!

**Comment by HeinzKetchupz** [comment] 2019-04-04 03:11
@KatNDusty Is the console and set command enabled in multitool enabled?

**Comment by KatNDusty** [comment] 2019-04-04 03:12
@HeinzKetchupz Yep, The console shows and I can type exec patch.txt into it but from there it just posts exec patch.txt into the chat

**Comment by KatNDusty** [comment] 2019-04-04 03:18
https://gyazo.com/97d0bc0c281afc828a74af08b1ede78a

**Comment by HeinzKetchupz** [comment] 2019-04-04 03:20
Did you delete the files in %localappdata%?
If not delete Hex and BLCMM folders then redo your paths and Settings in Hex.

**Comment by MyJumpsSuck** [comment] 2019-04-04 03:26
Im having the same issue where it puts it in chat, I can wait to play reborn until the new blmcm update and btw  thanks for all time spent fixing it today .

**Comment by KatNDusty** [comment] 2019-04-04 03:30
@HeinzKetchupz Yeah, just tried that. Same issue. Thanks for trying to help anyway guys. And thanks for all your hard work @c0dycode . I can wait to play until things are figured out. No issue!

**Comment by c0dycode** [comment] 2019-04-04 03:47
Here's version 1.21:
[BL Hex-Multitool .NET 4.5 - UHD Beta.zip](https://github.com/c0dycode/Borderlands-Hex-Multitool/files/3041649/BL.Hex-Multitool.NET.4.5.-.UHD.Beta.zip)

This one should ™️ add basic functionality for TPS aswell.

Took longer than expected and therefore I didn't have time yet to investigate some of the reported issues of the "say" not properly being patched. If you want, feel free to still give it a try. Maybe it was a bug that I accidentally fixed 😋 

Unfortunately this will be the last update from me for a few hours.

Been at it since 6pm and it's almost 6am now. So I'll go get some rest :)
Thanks for all the kind words and support everyone :) ❤️

**Comment by cfulton** [comment] 2019-04-04 03:52
didn't work

**Comment by HeinzKetchupz** [comment] 2019-04-04 04:34
@Everyone that this doesnt work for. Ive tried a couple a walk throughs with a friend and we have a kinds guide to use. Now this worked for 2 people so it might not work for you it may work for you. But its worth a try

1. Delete BLCMM and Older hexedit
2. Download the newest BLCMM and the newest Hex edit beta tool
3. Delete the files in %localappdata% for BLCMM and Hex Edit
4. Open the BLCMM you downloaded and Hex edit. Set the paths in Hex and check if the Tilde is set for  Hex and BLCMM. 
5. Open bl2 and check if exec blah blah works now

If this worked then Great
If not
Dont hunt me down im just trying to help

**Comment by c0dycode** [comment] 2019-04-04 11:35
@Default-Devv Alrighty, so I've just used the newest beta from above on your .exe and from manually checking it appears to be doing the hexediting properly.
Could you give that version a try? If that still doesn't work, make sure you don't have any third party Antivirus interfering with the Hexediting.

The ones that interfere with our tools the most are Avast and McAffee.

**Comment by sh3zb0t** [comment] 2019-04-04 11:54
should It exit without any prompt message after clicking "apply"?

**Comment by c0dycode** [comment] 2019-04-04 12:10
@sh3zb0t No, that should not be the case. I'm currently adding a few more things for better error handling. Hopefully that can help a little in finding out what's causing this for you. I'll let you know when that's ready :)

**Comment by c0dycode** [comment] 2019-04-04 12:54
New beta, version 1.22.
Most changes are to inform the user if a location could not be found or a different error occured.

[BL Hex-Multitool .NET 4.5 - UHD Beta 1.22.zip](https://github.com/c0dycode/Borderlands-Hex-Multitool/files/3043472/BL.Hex-Multitool.NET.4.5.-.UHD.Beta.1.22.zip)

Let me know if this fixes anything or still has the same/other issues.

**Comment by toasterm** [comment] 2019-04-04 13:23
still crashes after pressing apply when removing the sanity checks

**Comment by c0dycode** [comment] 2019-04-04 13:24
Can you verify your files via steam and then upload your exe so I can take a look?

**Comment by toasterm** [comment] 2019-04-04 13:30
how does one do that? im very new to modding borderlands

**Comment by c0dycode** [comment] 2019-04-04 13:31
In your Steamlibrary, right-click on the game and select "Properties",
then select the "Local Files" tab and click the "Verify integrity of game files..." button.

**Comment by toasterm** [comment] 2019-04-04 13:39
https://gyazo.com/257ed1c19eaccc5d1fba0f525f14a99f

**Comment by c0dycode** [comment] 2019-04-04 13:46
Yes, that is correct.
Now upload the Borderlands2.exe somewhere. You can find it by clicking in the same window, mentioned above, on "Browse local files..." instead.

From there go into the Binaries->Win32 folder. There you should see your Borderlands2(.exe)

**Comment by toasterm** [comment] 2019-04-04 13:53
where should i upload it and how do i do that?

**Comment by c0dycode** [comment] 2019-04-04 13:54
If you have a google account, you can just drag and drop it into your Google Drive.
You can find it here: https://drive.google.com/?tab=wo&authuser=0

Otherwise, things like mega, dropbox etc.

**Comment by Axelgrey** [comment] 2019-04-04 14:12
Just so you know, I'm getting a crash every time I try to apply too, but it still seems to have done the change.
Used BLCMM to enable console key, patched with HEX multitool afterwards causing a crash after apply, console works in game and the patch seems to work (no 'say' issue).

**Comment by toasterm** [comment] 2019-04-04 14:31
https://drive.google.com/open?id=11AnHIfG53UVUbNF20D2Up-B4f73pMZ_O

**Comment by c0dycode** [comment] 2019-04-04 14:33
@Axelgrey Can you hit me up on Discord? c0dycode#2049
@toasterm Thanks, I'll take a look at it :)

**Comment by bunta228** [comment] 2019-04-04 14:39
Verifying game files on steam and then hex editing with Multitool v1.22 works for BL2, can confirm

**Comment by c0dycode** [comment] 2019-04-04 15:16
Aaand here is version 1.23
[BL Hex-Multitool .NET 4.5 - UHD Beta 1.23.zip](https://github.com/c0dycode/Borderlands-Hex-Multitool/files/3044154/BL.Hex-Multitool.NET.4.5.-.UHD.Beta.1.23.zip)

This fixed the crashing when hitting Apply for @Axelgrey 
Thanks again for testing :)

Can you test this version @toasterm and @sh3zb0t ? :)

For everyone else that has issues with "say" not being patched properly, do you have any third-party antivirus software installed, like Avast or McAffee?

**Comment by toasterm** [comment] 2019-04-04 15:27
it doesnt crash for me its saying its already been patched so thanks :)

**Comment by toasterm** [comment] 2019-04-04 15:41
seems like the only issue now is the blcmm needing an update

**Comment by c0dycode** [comment] 2019-04-04 15:44
You can use BLCMM just fine, except for the Hexediting part. Which would be exactly the same ones as this tool provides :)

**Comment by toasterm** [comment] 2019-04-04 16:05
just checked and yeah it works now if the mod doesnt work then idk cus the hex editor worked as intended

**Comment by Th3Cartographer** [comment] 2019-04-04 17:08
![thing](https://user-images.githubusercontent.com/49285608/55574476-c81bcd00-570c-11e9-8910-f0acbefca2ff.png)
Same thing with and without anti-virus program, all set up correctly. Atleast i am able to save changes for TPS in hex tool.

**Comment by c0dycode** [comment] 2019-04-04 17:14
I'll be switching out the links to this version of 1.23
[https://github.com/c0dycode/Borderlands-Hex-Multitool/blob/master/BL%20Hex-Multitool%20.NET%204.5%20-%20UHD%20Beta.zip](url)

It has another little fix for the detection of the status for Set/Say Command Patching.

@Th3Cartographer Which version did you use? Also try verifying the game files via steam and try again. That has helped some people before.

**Comment by Axelgrey** [comment] 2019-04-04 17:16
Is the read-only thing fixed in this version or does it still need manual workaround?

**Comment by c0dycode** [comment] 2019-04-04 17:20
The read-only thing was an oversight from a disabled feature that was related to the installation of autoexec. It's no longer being used currently :)

**Comment by Chillipowda** [comment] 2019-04-04 17:23
Can confirm beta 1.23 multitool works
Steps taken -> delete blcmm and hexedit files in %appdata%/local (not the normal roaming folder the cmd prompt takes you to)
Verify integrity of game cache through steam
Use multitool as you're accustomed to

Should all be golden
Also, great work c0dy, this was a fast fix

**Comment by Th3Cartographer** [comment] 2019-04-04 20:00
@Chillipowda 
Yes it work.
Heres photo as a proof.
![work](https://user-images.githubusercontent.com/49285608/55584647-fb6a5600-5724-11e9-9bcc-2e74185f53e6.png)
Good job.

**Comment by pyromaniac420710** [comment] 2019-04-05 02:12
v1.23 Worked perfectly for me for bl2 sanity check, I edited the console and backpack space prior, but could not find the sanity check. Did them bastards at gearbox change those hex values, or was it just my hex editor?

**Comment by c0dycode** [comment] 2019-04-05 02:22
That was a mix of the gearbox patch and the Multitool. Glad you got it working though :)

**Comment by MyJumpsSuck** [comment] 2019-04-05 20:11
I don't think this is a problem with the hexedit but can anyone give me some advice, whenever I type in exec bl2reborn it works, but then I get into the game and nothing changed.

**Comment by Mio86** [comment] 2019-04-05 23:49
Worked great last night but logged in today and some features had broken. Eridium chest was back to keys and got the tunnel when loading in.  I exited and saved changes in the manager and reapplied patch in the multitool and it works for now. Love this game now btw, thanks for the awesome work!!!

**Comment by c0dycode** [comment] 2019-04-05 23:52
@Mio86 It seems like the UHD update caused some issues with Hotfix-Mods. If you see that changes are not as expected, go back to the main menu, execute the patch again and that should ™️ fix it.

**Comment by DankYeezy** [comment] 2019-04-06 01:28
Try verifying the files through steam then using UHD hex editor to disable sanity check. Should work after by that.

**Comment by Mio86** [comment] 2019-04-06 13:42
Tried reloading, it didn't work getting an message on the console (Unrecognized class or object Transient.SparkServiceConfiguration_6). Its repeats once

**Comment by c0dycode** [comment] 2019-04-06 13:58
That either means you're not waiting long enough before executing the patch or you're not connected with the Gearbox server.

**Comment by vasilvestre** [comment] 2019-04-06 19:47
Crash game after end of cinematics. i am the only one here ?

**Comment by insanebananna** [comment] 2019-04-06 19:51
> Can confirm beta 1.23 multitool works
> Steps taken -> delete blcmm and hexedit files in %appdata%/local (not the normal roaming folder the cmd prompt takes you to)
> Verify integrity of game cache through steam
> Use multitool as you're accustomed to
> 
> Should all be golden
> Also, great work c0dy, this was a fast fix

i'm having a great bit of trouble finding the files you mentioned and i'm still totally unable to use the mod despite getting the new hex editor, i'm stuck on getting the text only response to using exec bl2reborn.txt  can you tell me more about how you got it working?

**Comment by insanebananna** [comment] 2019-04-06 19:53
> Try verifying the files through steam then using UHD hex editor to disable sanity check. Should work after by that.

i've done this and the hex edit seems to be working fine but i can't get a response from using the prompt to open the mod using the exec command

**Comment by c0dycode** [comment] 2019-04-06 20:04
@vasilvestre First time that I hear about such an issue. Have you tried verifying the game files via steam?

@insanebananna Do you mean you cannot open the console to enter the command?


I'll also close this issue now, since the initial reported issue has been resolved and 22 people get an E-Mail at this point whenever somebody replies in here.

If you believe that this tool is responsible for any issues/or is not working as expected, feel free to open up a new issue.

**Closed by c0dycode** 2019-04-06 20:04 UTC

**Comment by insanebananna** [comment] 2019-04-06 20:07
> @vasilvestre First time that I hear about such an issue. Have you tried verifying the game files via steam?
> 
> @insanebananna Do you mean you cannot open the console to enter the command?
> 
> I'll also close this issue now, since the initial reported issue has been resolved and 22 people get an E-Mail at this point whenever somebody replies in here.
> 
> If you believe that this tool is responsible for any issues/or is not working as expected, feel free to open up a new issue.

no i don't believe any of the tools are to be blamed or wrong in any fashion. i've verified the files through steam, i've used the new hexedit tool and it is all good but i just can't get the exec bl2reborn.txt to take effect. i just get a text version of it and it doesn't actually do anything.

**Comment by c0dycode** [comment] 2019-04-06 20:11
If you're on Discord, feel free to DM me and I'll try to help you out :)

c0dycode#2049

**Comment by insanebananna** [comment] 2019-04-06 20:21
barbiesrevenge#4843 i can't dm you without you adding me, at least that's what it's saying on discord

**Comment by vasilvestre** [comment] 2019-04-06 21:04
> @vasilvestre First time that I hear about such an issue. Have you tried verifying the game files via steam?

Yes

**Comment by nucleardragon85** [comment] 2019-04-07 00:21
I've deleted all mods and deleted BL2 and then I reinstalled BL2but it doesn't start up from steam at all.

**Comment by insanebananna** [comment] 2019-04-07 00:32
The issue has been fixed thank you to everyone that helped.
