### ISSUE TITLE
update needed. 

### ISSUE THREAD

**Issue by Themightyhook** [c0dycode/Borderlands-Hex-Multitool#55] opened 2021-09-10 02:49 UTC
bl2 and pre-sequel got updates that broken the hex tool. would not be shocked if the updates was only to break the hex tool.

**Comment by c0dycode** [comment] 2021-09-10 05:14
I won't be home from work for about another 10 hours. I'll take a look once I am though.

**Comment by c0dycode** [comment] 2021-09-10 17:48
Should be fixed with 1.39 now :)

Let me know if you run into any issues!

**Comment by Themightyhook** [comment] 2021-09-10 23:40
alright! i make sure too

**Comment by Themightyhook** [comment] 2022-07-21 23:00
another update seems to broken the editor again

**Comment by MikhailaTF** [comment] 2022-08-08 18:42
> another update seems to broken the editor again

I second this.

**Comment by c0dycode** [comment] 2022-08-09 04:37
Did this update fix the issue that they introduced with the previous one?
After the previous update they tweeted that they're working on a fix, therefore I did not work on an update yet.

**Comment by MikhailaTF** [comment] 2022-08-09 08:49
What would the issue be? I'm a scrub that doesn't have a twitter account/doesn't pay attention to twitter so I'm unaware of this hah.

**Comment by c0dycode** [comment] 2022-08-13 08:35
IIRC, the game was just crashing and it was caused by an update to their in-game "news".
Either way, I'm working on the update right now. Should be up in a couple hours max.

**Comment by c0dycode** [comment] 2022-08-13 10:07
Version 1.40 should be uploaded now 👍

**Closed by c0dycode** 2022-08-13 10:07 UTC
